### ISSUE TITLE
Battery/Grid In and Out semantics

### ISSUE THREAD

**Issue by pmyers** [Haluska77/solar-gauge-card#2]
Hi! First off, thanks for creating this card. I just got a solar system set up, and this is a really nice visualization to use on an overview dashboard for Home Assistant.

I did have one question (possibly an issue report). My yaml is as follows:
```
type: custom:solar-gauge-card
solarPower:
  entity: sensor.sol_ark_pv_power
homeConsumption:
  entity: sensor.sol_ark_load_power
gridPower:
  entity: sensor.sol_ark_grid_power
batteryPower:
  entity: sensor.sol_ark_battery_power
battery:
  capacity:
    entity: sensor.sol_ark_battery_state_of_charge
  temperature:
    entity: sensor.sol_ark_battery_temperature
gaugeWidth: 20
```

But when I'm charging the battery, it displays as Battery Out, and not Battery In. Is this a bug or am I configuring something incorrectly?

![Image](https://github.com/user-attachments/assets/d0b09dbd-2ea2-40ee-b6fd-0f0715c1a2f1)

I would think that Battery Out means "power coming from the battery to my house/inverter" and Battery In would be "power going into (charging) my battery from the inverter". But if you're looking at it differently, let me know.

I have the same question about the semantics of Grid Out and Grid In, which from my perspective also seem reversed.

Thanks!

Perry
